#!/bin/bash

cd /Users/nhutvo/Projects/ethereum-tx-inspector/src/temper
git checkout develop && git pull origin develop;
docker build . -t 10.123.31.221:5000/temper:latest &&  docker push 10.123.31.221:5000/temper:latest