apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ethereum-tx
  name: temper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temper
      version: v1
  template:
    metadata:
      labels:
        app: temper
        version: v1
    spec:
      containers:
      - name: temper
        image: 10.123.31.221:5000/temper:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        envFrom:
          - configMapRef:
              name: temper-config
          - secretRef:
              name: temper-secret
