substitutions:
  _IMAGE_NAME: 'us-docker.pkg.dev/sumica-production/gcr.io/temper'
  _GIT_REPO_INFRA: 'github.com/wakumo/wakumo-production-gke.git'
  _DEPLOYMENT_PATH: 'namespaces/ethereum-tx/temper/resources'
  _GIT_BRANCH: 'main'
  _GIT_USERNAME: 'chauphamwakumo'
  _GIT_EMAIL: 'chaupham@wakumo.vn'
  _INFRA_REPO: 'wakumo-production-gke'

  _DEPLOYMENT_FILE: 'temper-deployment.yml'
  _COMMIT_PREFIX: '[Cloud Builder]'

availableSecrets:
  secretManager:
  - versionName: projects/966524086068/secrets/GIT_ACCESS_TOKEN/versions/latest
    env: 'GIT_ACCESS_TOKEN'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_IMAGE_NAME}:$REF_NAME', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args:
  - -c
  - |
    docker push ${_IMAGE_NAME}:$REF_NAME

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://${_GIT_USERNAME}:$$GIT_ACCESS_TOKEN@${_GIT_REPO_INFRA}
    cd ${_INFRA_REPO}
    git checkout ${_GIT_BRANCH}
    cd ${_DEPLOYMENT_PATH}
    sed -i "s|image: ${_IMAGE_NAME}[^[:space:]]*|image: ${_IMAGE_NAME}:$REF_NAME|g" ${_DEPLOYMENT_FILE}
    git config --global user.name "${_GIT_USERNAME}"
    git config --global user.email "${_GIT_EMAIL}"
    git add -A
    git commit -m "${_COMMIT_PREFIX} Updated image tag ${_IMAGE_NAME}:$REF_NAME from commit $COMMIT_SHA"
    git push origin ${_GIT_BRANCH}
